version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./backend
    expose: 
      - 3003
    ports:
      - 3003:3003
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  client:
    container_name: client
    restart: always
    build: ./frontend
    expose: 
      - 8080
    ports:
      - 8080:8080
    links:
      - app
